# Generated by Django 3.2.25 on 2024-07-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
