# Generated by Django 3.2.25 on 2024-07-24 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_alter_goal_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='amount',
        ),
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
